spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webtoon_hub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: webtoon
    password: webtoon
  sql:
    init:
      mode: always
